<?php


namespace app\mobile\controller;


use app\model\Cate;
use think\facade\View;

class Booklist extends Base
{
    protected $bookService;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->bookService = app('bookService');
    }

    public function index() {
        $cates = cache('cates');
        if (!$cates) {
            $cates = Cate::select();
            cache('cates:boys', $cates, 'null', 'redis');
        }

        $cate_selector = -1;
        $words_selector = -1;
        $end_selector = -1;

        $map = array();
        $cate = (int)input('sortid');
        $cate_name = '全部';
        $cate_model = Cate::where('sortid', $cate)->find();
        if (isset($cate_model)) {
            $cate_name = $cate_model->cate_name;
        }
        if ($cate == 0 || $cate == -1) {

        } else {
            $map[] = ['sortid', '=', $cate];
            $cate_selector = $cate;
        }
//        $arr = array();
//        if ($cate == 0 || $cate == '-1') {
//            foreach ($cates as $c) {
//                array_push($arr, $c['sortid']);
//            }
//        } else {
//            array_push($arr, $cate);
//            $cate_selector = $cate;
//        }

        $words = (int)input('words');
        if ($words == 0 || $words == '-1') {

        } else {
            $map[] = ['words', '<=', $words];
            $words_selector = $words;
        }
        $fullflag = (int)input('fullflag');
        if ($fullflag == -1) {

        } else {
            $map[] = ['fullflag', '=', $fullflag];
            $end_selector = $fullflag;
        }
        $data = $this->bookService->getPagedBooks(20, $this->end_point, 'articleid', $map);
        unset($data['page']['query']['page']);
        $param = '';
        foreach ($data['page']['query'] as $k => $v) {
            $param .= '&' . $k . '=' . $v;
        }

        View::assign([
            'books' => $data['books'],
            'cates' => $cates,
            'cate_selector' => $cate_selector,
            'words_selector' => $words_selector,
            'end_selector' => $end_selector,
            'page' => $data['page'],
            'param' => $param,
            'cate' => $cate_name,
            'header' => '小说书库',
        ]);
        return view($this->tpl);
    }
}