<?php


namespace app\admin\controller;


use app\model\Tags;
use app\service\TagsService;
use Overtrue\Pinyin\Pinyin;
use think\db\exception\DataNotFoundException;
use think\db\exception\ModelNotFoundException;
use think\exception\ValidateException;
use think\facade\Db;
use think\facade\View;

class Tag extends Base
{
    protected $tagsService;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->tagsService = app('tagsService');
    }

    public function index(){
        $data = $this->tagsService->getPagedAdmin();
        View::assign([
            'tags' => $data['tags'],
            'count' => $data['count']
        ]);
        return view();
    }

    public function create(){
        if (request()->isPost()) {
            $tag = new Tags();
            $tag->tag_name = input('tag_name');
            $tag->pinyin = input('pinyin');
            $tag->jianpin = input('jianpin');
            $result = $tag->save();
            if ($result) {
                return json(['err' =>0,'msg'=>'添加成功']);
            }else{
                return json(['err' =>1,'msg'=>'添加失败']);
            }
        }
        return view();
    }

    public function edit(){
        $id = input('id');
        try {
            $tag = Tags::findOrFail($id);
            if (request()->isPost()) {
                $tag->tag_name = input('tag_name');
                $tag->pinyin = input('pinyin');
                $tag->jianpin = input('jianpin');
                $result = $tag->save();
                if ($result) {
                    return json(['err' =>0,'msg'=>'修改成功']);
                }else{
                    return json(['err' =>1,'msg'=>'修改失败']);
                }
            }
            View::assign([
                'tag' => $tag,
            ]);
            return view();
        } catch (DataNotFoundException $e) {
            abort(404, $e->getMessage());
        } catch (ModelNotFoundException $e) {
            abort(404, $e->getMessage());
        }
    }

    public function import() {
        if (request()->isPost()) {
            $pinyin = new Pinyin();
            $file = request()->file('txt');
            $handle = fopen($file, "rb");
            if ($handle) {
                while (($line = fgets($handle)) !== false) {
                    $tag = Tags::where('tag_name','=',trim($line))->find();
                    if (is_null($tag)) {
                        $tag = new Tags();
                        $tag->tag_name = trim($line);
                        $tag->pinyin = $pinyin->permalink($line,'');
                        $tag->jianpin = $pinyin->abbr($line,'');
                        $tag->save();
                        echo '成功导入关键词'.$line;
                        ob_flush(); //将 php buffer 数据强制输出到 tcp buffer
                        flush(); // 将 tcp buffer 数据强制输出到浏览器
                    }
                }
                fclose($handle);
                echo '导入完成';
            } else {
                echo '导入失败';
            }
        } else {
            return view();
        }
    }
}