<?php


namespace app\admin\controller;


use app\model\SystemUsers;
use app\model\User;
use think\db\exception\DataNotFoundException;
use think\db\exception\ModelNotFoundException;
use think\facade\View;

class Users extends Base
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        return view();
    }

    public function list()
    {
        $page = intval(input('page'));
        $limit = intval(input('limit'));
        $data = SystemUsers::where('groupid', '=', 2);
        $count = $data->count();
        $users = $data->order('uid', 'desc')
            ->limit($page - 1, $limit)->select();
        return json([
            'code' => 0,
            'msg' => '',
            'count' => $count,
            'data' => $users
        ]);
    }

    public function search()
    {
        $uname = input('uname');
        $where[] = ['groupid', '=', 2];
        $where[] = ['uname', 'like', '%' . $uname . '%'];
        $page = intval(input('page'));
        $limit = intval(input('limit'));
        $data = SystemUsers::where($where);
        $count = $data->count();
        $users = $data->order('uid', 'desc')
            ->limit($page - 1, $limit)->select();
        return json([
            'code' => 0,
            'msg' => '',
            'count' => $count,
            'data' => $users
        ]);
    }

    public function edit()
    {
        $data = request()->param();
        try {
            $admin = SystemUsers::where('uid', '=', $data['uid'])->findOrFail();
            if (request()->isPost()) {
                $admin->uname = $data['uname'];
                if (empty($data['password']) || is_null($data['password'])) {

                } else {
                    $admin->pass = md5(trim($data['password']) . 'abc');
                }
                $result = $admin->save();
                if ($result) {
                    return json(['err' => 0, 'msg' => '修改成功']);
                } else {
                    return json(['err' => 1, 'msg' => '修改失败']);
                }
            }
            View::assign([
                'admin' => $admin,
            ]);
        } catch (ModelNotFoundException $e) {
            return json(['err' => 1, 'msg' => $e->getMessage()]);
        }
        return view();
    }

    public function delete()
    {
        $uid = input('uid');
        $result = SystemUsers::destroy($uid);
        if ($result) {
            return json(['err' => '0', 'msg' => '删除成功']);
        } else {
            return json(['err' => '1', 'msg' => '删除失败']);
        }
    }
}